version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - .env
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3000:3000
    volumes:
      - .:/app_name
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    depends_on:
      - db
      - selenium
  db:
    image: mysql:5.7
    ports:
      - "4306:3306"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
  selenium:
    image: selenium/standalone-chrome-debug:latest
    shm_size: 256m
    ports:
      - "5900:5900"
  # web:
  #   build:
  #     context: containers/nginx
  #   volumes:
  #     - public-data:/webapp/public
  #     - tmp-data:/webapp/tmp
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
